"""init py import 14

Revision ID: 091b15a0aa6a
Revises: 3fba47254fcf
Create Date: 2023-02-04 18:20:21.541435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091b15a0aa6a'
down_revision = '3fba47254fcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey'))
    )
    op.create_table('singers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('singers_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', 'company_id', name=op.f('singers_pkey'))
    )
    op.create_index(op.f('singers_company_id_idx'), 'singers', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('singers_company_id_idx'), table_name='singers')
    op.drop_table('singers')
    op.drop_table('companies')
    # ### end Alembic commands ###
