"""back popluate -> backref 5

Revision ID: 0f53e3014219
Revises: 7310ff165633
Create Date: 2023-02-04 19:48:17.283927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f53e3014219'
down_revision = '7310ff165633'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'created_at')
    # ### end Alembic commands ###
