"""init py import 9

Revision ID: 13f7bbf40dd6
Revises: 6ef4c705a948
Create Date: 2023-02-04 17:53:30.109803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f7bbf40dd6'
down_revision = '6ef4c705a948'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
