"""back popluate -> backref

Revision ID: 1f52ab5332aa
Revises: 091b15a0aa6a
Create Date: 2023-02-04 19:10:03.373530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f52ab5332aa'
down_revision = '091b15a0aa6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
