"""init py import 4

Revision ID: 253df4f51d07
Revises: c2efc50235e4
Create Date: 2023-02-04 17:33:59.402651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253df4f51d07'
down_revision = 'c2efc50235e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
