"""init py import 5

Revision ID: 27868465f645
Revises: 253df4f51d07
Create Date: 2023-02-04 17:38:30.411228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27868465f645'
down_revision = '253df4f51d07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
