"""init py import 13

Revision ID: 3fba47254fcf
Revises: 7cc2ac789cb3
Create Date: 2023-02-04 18:14:30.075570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fba47254fcf'
down_revision = '7cc2ac789cb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
