"""init py import 7

Revision ID: 412693558185
Revises: 4e9831892fdf
Create Date: 2023-02-04 17:45:12.535133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412693558185'
down_revision = '4e9831892fdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
