"""init py import 11

Revision ID: 54c42584f37c
Revises: b0b9d66fbdb6
Create Date: 2023-02-04 18:10:05.377626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c42584f37c'
down_revision = 'b0b9d66fbdb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
