"""alter table nullable

Revision ID: 59fd4b628b99
Revises: d42477f637d6
Create Date: 2023-01-07 19:33:08.965606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59fd4b628b99'
down_revision = 'd42477f637d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('town', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('town', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('town', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('town', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('town', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('town', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('city', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
