"""back popluate -> backref 3

Revision ID: 60818a4c68f9
Revises: 770122c7a5e6
Create Date: 2023-02-04 19:36:10.401786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60818a4c68f9'
down_revision = '770122c7a5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
