"""back popluate -> backref 4

Revision ID: 7310ff165633
Revises: 60818a4c68f9
Create Date: 2023-02-04 19:43:06.770290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7310ff165633'
down_revision = '60818a4c68f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
