"""init py import 2

Revision ID: 73dd1bb7b9b3
Revises: af3a0c2b1e8e
Create Date: 2023-02-04 17:25:08.170196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73dd1bb7b9b3'
down_revision = 'af3a0c2b1e8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
