"""back popluate -> backref 2

Revision ID: 770122c7a5e6
Revises: 1f52ab5332aa
Create Date: 2023-02-04 19:14:02.495624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770122c7a5e6'
down_revision = '1f52ab5332aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
