"""init py import 12

Revision ID: 7cc2ac789cb3
Revises: 54c42584f37c
Create Date: 2023-02-04 18:13:36.655473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc2ac789cb3'
down_revision = '54c42584f37c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
