"""create new models

Revision ID: 9beee4db8634
Revises: b96b19d07595
Create Date: 2023-02-12 15:55:00.904529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9beee4db8634'
down_revision = 'b96b19d07595'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey'))
    )
    op.create_table('singers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('singers_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('singers_pkey'))
    )
    op.create_index(op.f('singers_company_id_idx'), 'singers', ['company_id'], unique=False)
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('singer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['singer_id'], ['singers.id'], name=op.f('albums_singer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('albums_pkey'))
    )
    op.create_index(op.f('albums_singer_id_idx'), 'albums', ['singer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('albums_singer_id_idx'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('singers_company_id_idx'), table_name='singers')
    op.drop_table('singers')
    op.drop_table('companies')
    # ### end Alembic commands ###
