"""init py import 

Revision ID: af3a0c2b1e8e
Revises: d892fe99f685
Create Date: 2023-02-04 17:22:47.067897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3a0c2b1e8e'
down_revision = 'd892fe99f685'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
