"""init py import 10

Revision ID: b0b9d66fbdb6
Revises: 13f7bbf40dd6
Create Date: 2023-02-04 18:08:49.077185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b9d66fbdb6'
down_revision = '13f7bbf40dd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
