"""init py import 3

Revision ID: c2efc50235e4
Revises: 73dd1bb7b9b3
Create Date: 2023-02-04 17:27:23.500267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2efc50235e4'
down_revision = '73dd1bb7b9b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
