"""create new table : plz

Revision ID: d892fe99f685
Revises: 22c0d6aa967e
Create Date: 2023-02-04 17:21:56.259283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd892fe99f685'
down_revision = '22c0d6aa967e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
